# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1825b51d8a8db46276bac4824e765eb870b948985d3bf336eafdca21274a4b06c903da7dcf2fde529b31fbbc6333f1bf38d25169317d77f8adc266871a90cf78

test:
  secret_key_base: d361b6458ded499061700500054fe4442a9324850d44e18ccc5fec5b850c7413987a0584d87157eb805c781d67710f600775a95182124cee6a6135c3018b84b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
